import { createThemedDeckAdapter } from './themeAdapter';
import type { ThemedCard, ThemedDeckConfig, ThemedReading } from './themedTarot';
import type { ReadingRequest } from './readingTypes';

export const shipSpreads = ['single', 'three-card', 'choice', 'celtic-cross'] as const;

export const shipCards: Record<string, ThemedCard> = {
  'the-fool': {
    tarotId: 'the-fool',
    title: '开新坑',
    archetype: '机会很新，假设还很薄',
    caption: '先做一个能跑起来的版本，别急着写十年路线图。',
    uprightMeaning: '适合启动、试水和用低成本验证方向。不要等到所有条件完美才开始。',
    reversedMeaning: '可能是在用新鲜感逃避现实约束。先确认风险、边界和最小下一步。',
    emotionalSignal: '兴奋、未知、轻装启动',
    tinyAction: '把这个想法缩成一个今天能完成的 30 分钟实验。',
    shareText: 'ShipTarot：今天适合开一个小坑，但别把坑挖成峡谷。',
    palette: 'violet',
    sigil: '0',
  },
  'the-magician': {
    tarotId: 'the-magician',
    title: '工具齐了',
    archetype: '资源可用，差的是调度',
    caption: '你不是缺魔法，你是还没把手边工具接起来。',
    uprightMeaning: '当前最适合把已有资源组合成动作。做原型、写脚本、接 API 都比继续想更有效。',
    reversedMeaning: '可能在堆工具、换框架或炫技。先问：这个动作是否真的推进结果。',
    emotionalSignal: '掌控、执行、组合、手感',
    tinyAction: '列出已有资源，选择一个直接服务当前目标。',
    shareText: 'ShipTarot：工具栏已经亮了，现在该点运行。',
    palette: 'grape',
    sigil: 'I',
  },
  'the-high-priestess': {
    tarotId: 'the-high-priestess',
    title: '沉默信号',
    archetype: '数据还没说全，但直觉已经报警',
    caption: '别忽略那些没人明说、但每次评审都会绕开的东西。',
    uprightMeaning: '先观察隐藏信息。用户反馈、团队沉默和反复出现的犹豫都值得被记录。',
    reversedMeaning: '你可能把含糊当深刻，或者逃避该问清楚的问题。',
    emotionalSignal: '直觉、暗线、未说出口',
    tinyAction: '写下一个最不想问但最该问的问题。',
    shareText: 'ShipTarot：会议没说出口的部分，往往才是正文。',
    palette: 'indigo',
    sigil: 'II',
  },
  'the-empress': {
    tarotId: 'the-empress',
    title: '滋养体验',
    archetype: '产品要能被舒服地使用',
    caption: '增长之前，先让人愿意留下。',
    uprightMeaning: '体验、文案、节奏和情绪价值正在成为关键。把用户当真实的人，而不是漏斗数字。',
    reversedMeaning: '可能过度照顾边缘细节，却忘了核心价值是否成立。',
    emotionalSignal: '滋养、体验、耐心打磨',
    tinyAction: '优化一个用户会反复遇到的小摩擦。',
    shareText: 'ShipTarot：今天先把体验养肥一点。',
    palette: 'pink',
    sigil: 'III',
  },
  'the-emperor': {
    tarotId: 'the-emperor',
    title: '立规矩',
    archetype: '边界、架构和责任归属',
    caption: '没有结构，热情会变成散装噪音。',
    uprightMeaning: '需要明确负责人、范围、节奏和验收标准。结构会释放执行力。',
    reversedMeaning: '控制欲可能压过了真实问题。规则太硬会让团队只学会绕路。',
    emotionalSignal: '秩序、边界、治理',
    tinyAction: '写下这件事的非目标和验收线。',
    shareText: 'ShipTarot：边界清楚，推进才不打滑。',
    palette: 'red',
    sigil: 'IV',
  },
  'the-hierophant': {
    tarotId: 'the-hierophant',
    title: '参考范式',
    archetype: '先学成熟做法，再决定哪里创新',
    caption: '不是所有轮子都值得重新发明。',
    uprightMeaning: '现在适合参考已有标准、库、模板或行业惯例。复用会让你更快抵达核心差异。',
    reversedMeaning: '你可能被惯例绑住，或者复制了不适合自己场景的流程。',
    emotionalSignal: '规范、传承、复用',
    tinyAction: '找一个成熟实现，明确哪些直接复用、哪些必须改。',
    shareText: 'ShipTarot：先 import，再 invent。',
    palette: 'gray',
    sigil: 'V',
  },
  'the-lovers': {
    tarotId: 'the-lovers',
    title: '关键取舍',
    archetype: '选择会暴露真正价值观',
    caption: '路线不是都要，用户也不是都要。',
    uprightMeaning: '需要做清楚的选择。越早承认偏好和优先级，后面越少内耗。',
    reversedMeaning: '摇摆、迎合或双线并行可能正在稀释结果。',
    emotionalSignal: '选择、对齐、价值判断',
    tinyAction: '把当前选择写成“选 A 就放弃 B”。',
    shareText: 'ShipTarot：真正的选择，总会带一点舍不得。',
    palette: 'rose',
    sigil: 'VI',
  },
  'the-chariot': {
    tarotId: 'the-chariot',
    title: '冲刺窗口',
    archetype: '方向明确时就该加速',
    caption: '现在不是继续开会，是把车开出去。',
    uprightMeaning: '适合冲刺、发布、推进和集中火力。保持方向，不要被每个噪声拉走。',
    reversedMeaning: '速度可能掩盖方向问题。乱冲会制造更多返工。',
    emotionalSignal: '推进、专注、节奏拉满',
    tinyAction: '只保留一个冲刺目标，并砍掉一个干扰项。',
    shareText: 'ShipTarot：油门可以踩，但方向盘也要握住。',
    palette: 'blue',
    sigil: 'VII',
  },
  strength: {
    tarotId: 'strength',
    title: '稳定推进',
    archetype: '用耐心驯服复杂度',
    caption: '真正的强不是硬推，是每天都能继续。',
    uprightMeaning: '这件事需要温和但持续的力量。小步、复盘和稳定节奏比爆发更可靠。',
    reversedMeaning: '可能在硬撑、急躁或用情绪替代判断。',
    emotionalSignal: '耐心、韧性、节奏',
    tinyAction: '把一个大任务拆成今天能稳定完成的小块。',
    shareText: 'ShipTarot：别硬刚，稳稳地把它推过去。',
    palette: 'orange',
    sigil: 'VIII',
  },
  'the-hermit': {
    tarotId: 'the-hermit',
    title: '深工时间',
    archetype: '退到安静处找答案',
    caption: '有些问题不能靠群聊解决。',
    uprightMeaning: '需要独立思考、深度阅读或关掉通知。答案可能在安静里浮出来。',
    reversedMeaning: '闭门造车或过度孤立会让判断失真。',
    emotionalSignal: '独处、研究、内在导航',
    tinyAction: '留一段不被打断的深工时间，只处理一个难点。',
    shareText: 'ShipTarot：先离线一下，系统正在重建索引。',
    palette: 'dark',
    sigil: 'IX',
  },
  'wheel-of-fortune': {
    tarotId: 'wheel-of-fortune',
    title: '周期切换',
    archetype: '时机、波动和外部变量',
    caption: '不是所有变化都由你控制，但你能调整姿态。',
    uprightMeaning: '局势正在变化。顺势调整比坚持旧计划更有效。',
    reversedMeaning: '可能陷入重复循环，同样的问题以不同名字回来。',
    emotionalSignal: '变化、窗口、循环',
    tinyAction: '找出一个反复出现的模式，并换一种处理方式。',
    shareText: 'ShipTarot：风向变了，帆也该动一下。',
    palette: 'cyan',
    sigil: 'X',
  },
  justice: {
    tarotId: 'justice',
    title: '验收标准',
    archetype: '事实、责任和后果',
    caption: '感觉不错不算通过，标准说了算。',
    uprightMeaning: '需要更清楚的数据、标准和责任边界。把争论拉回事实。',
    reversedMeaning: '可能存在偏见、模糊验收或选择性看数据。',
    emotionalSignal: '判断、标准、公平',
    tinyAction: '定义一个可以被验证的成功指标。',
    shareText: 'ShipTarot：让标准发言，情绪先旁听。',
    palette: 'teal',
    sigil: 'XI',
  },
  'the-hanged-man': {
    tarotId: 'the-hanged-man',
    title: '换个视角',
    archetype: '暂停、倒置和重新理解',
    caption: '卡住不一定是坏事，可能是问题问错了。',
    uprightMeaning: '先暂停，不要急着加速。换一个问题，可能比找更多答案有效。',
    reversedMeaning: '拖延可能被包装成等待。需要分清暂停和停滞。',
    emotionalSignal: '暂停、换框架、等待',
    tinyAction: '把当前问题改写成另一个问法。',
    shareText: 'ShipTarot：先把图倒过来看。',
    palette: 'lime',
    sigil: 'XII',
  },
  death: {
    tarotId: 'death',
    title: '关掉旧线',
    archetype: '结束旧版本，释放新空间',
    caption: '不是每个功能都值得继续供电。',
    uprightMeaning: '适合下线、归档、砍 scope 或结束无效承诺。结束是资源回收。',
    reversedMeaning: '你可能明知该停，却因为沉没成本继续拖。',
    emotionalSignal: '结束、转化、清理',
    tinyAction: '关闭一个不再服务目标的任务、文件或承诺。',
    shareText: 'ShipTarot：删掉旧分支，主线才清楚。',
    palette: 'dark',
    sigil: 'XIII',
  },
  temperance: {
    tarotId: 'temperance',
    title: '调节配比',
    archetype: '节奏、混合和系统平衡',
    caption: '不是更多，是刚刚好。',
    uprightMeaning: '需要调和资源、节奏和优先级。稳定系统比短期峰值更重要。',
    reversedMeaning: '节奏失衡，可能过载、过慢或目标互相打架。',
    emotionalSignal: '平衡、恢复、配比',
    tinyAction: '从今天安排里删掉一个不必要的负载。',
    shareText: 'ShipTarot：把系统调回可持续模式。',
    palette: 'yellow',
    sigil: 'XIV',
  },
  'the-devil': {
    tarotId: 'the-devil',
    title: '上头陷阱',
    archetype: '诱惑、锁定和隐性代价',
    caption: '指标很好看，但它可能在喂错东西。',
    uprightMeaning: '某个诱惑正在绑定你。看清它给你的奖励，也看清它拿走什么。',
    reversedMeaning: '你开始看见束缚来源，这是解绑的第一步。',
    emotionalSignal: '沉迷、依赖、短期奖励',
    tinyAction: '给一个上头行为设置停止线。',
    shareText: 'ShipTarot：别让爽感冒充战略。',
    palette: 'red',
    sigil: 'XV',
  },
  'the-tower': {
    tarotId: 'the-tower',
    title: '结构报警',
    archetype: '崩塌、暴露和重新搭建',
    caption: '它不是突然坏的，只是今天终于藏不住了。',
    uprightMeaning: '旧结构可能撑不住了。震动不舒服，但它暴露真问题。',
    reversedMeaning: '你已经看到裂缝，却仍在避免必要调整。',
    emotionalSignal: '突变、故障、真相',
    tinyAction: '承认一个明显问题，并停止替它找借口。',
    shareText: 'ShipTarot：事故报告也是路线图。',
    palette: 'orange',
    sigil: 'XVI',
  },
  'the-star': {
    tarotId: 'the-star',
    title: '恢复信心',
    archetype: '希望、修复和长期感',
    caption: '不是鸡血，是系统恢复了呼吸。',
    uprightMeaning: '适合修复信任、补充能量和重新看到长期方向。',
    reversedMeaning: '可能过累，看不见希望。先恢复系统，再谈远方。',
    emotionalSignal: '希望、疗愈、续航',
    tinyAction: '做一件能恢复信心的小事，而不是立刻解决全部。',
    shareText: 'ShipTarot：先把灯重新点亮。',
    palette: 'cyan',
    sigil: 'XVII',
  },
  'the-moon': {
    tarotId: 'the-moon',
    title: '迷雾需求',
    archetype: '不确定、投射和信息缺口',
    caption: '用户说的、你听到的、真实发生的，可能不是一回事。',
    uprightMeaning: '信息不完整，适合做访谈、日志分析和风险拆解。别急着定案。',
    reversedMeaning: '迷雾开始散开，可以把焦虑拆成可验证事实。',
    emotionalSignal: '不确定、焦虑、潜台词',
    tinyAction: '把最坏想象和可验证事实分成两列。',
    shareText: 'ShipTarot：先把雾量化。',
    palette: 'indigo',
    sigil: 'XVIII',
  },
  'the-sun': {
    tarotId: 'the-sun',
    title: '清晰上线',
    archetype: '可见、简单和正反馈',
    caption: '好东西终于不用解释半天了。',
    uprightMeaning: '方向变清楚了。适合发布、展示、复盘成果和强化正反馈。',
    reversedMeaning: '亮点被遮住了，可能是表达、渠道或信心问题。',
    emotionalSignal: '清晰、快乐、正反馈',
    tinyAction: '把一个好结果说清楚，并让更多人看见。',
    shareText: 'ShipTarot：今天适合把灯打开。',
    palette: 'yellow',
    sigil: 'XIX',
  },
  judgement: {
    tarotId: 'judgement',
    title: '复盘召唤',
    archetype: '被提醒、被唤醒、重新决定',
    caption: '不是又开会，是这次真的要学到东西。',
    uprightMeaning: '适合复盘、重新承诺和对过去经验做出回应。',
    reversedMeaning: '可能听见了问题，却还在装没听见。',
    emotionalSignal: '觉醒、复盘、决定',
    tinyAction: '写下这次和上次相比必须不同的一点。',
    shareText: 'ShipTarot：复盘不是仪式，是改命令。',
    palette: 'violet',
    sigil: 'XX',
  },
  'the-world': {
    tarotId: 'the-world',
    title: '闭环完成',
    archetype: '整合、发布和阶段完成',
    caption: '把事情收好，才算真的 ship。',
    uprightMeaning: '一个阶段可以收束。适合发布、归档、庆祝和把经验写成系统。',
    reversedMeaning: '还有尾巴没收，别让 95% 完成长期占用注意力。',
    emotionalSignal: '完成、整合、闭环',
    tinyAction: '把一个已完成事项正式归档或发布。',
    shareText: 'ShipTarot：关单也是一种仪式感。',
    palette: 'teal',
    sigil: 'XXI',
  },
};

export const shipDeckConfig: ThemedDeckConfig = {
  id: 'shiptarot',
  productName: 'ShipTarot',
  taskName: 'shiptarot_project_reading',
  cardLabel: '推进牌',
  archetypeLabel: '项目原型',
  uprightLabel: '顺风',
  reversedLabel: '逆风',
  emptyQuestion: '用户没有输入具体项目问题，请围绕当前推进状态进行分析。',
  fallbackShareText: 'ShipTarot：把项目状态翻译成一张推进牌。',
  promptIdentity: '你的任务是把传统塔罗含义翻译成项目推进、产品决策和执行节奏的自我观察。',
  promptVoice: '像一个冷静但有幽默感的产品/工程搭档，具体、可执行、不宿命化。',
  promptBoundary: '项目语言是解释入口，传统塔罗含义仍是分析骨架。',
  cards: shipCards,
  spreadIds: shipSpreads,
};

const shipAdapter = createThemedDeckAdapter(shipDeckConfig);

export type ShipReading = ThemedReading;

export function createShipReading(params: ReadingRequest) {
  return shipAdapter.createReading(params);
}

export function createShipSynthesis(reading: ShipReading) {
  return shipAdapter.createSynthesis(reading);
}

export function buildShipPayload(reading: ShipReading) {
  return shipAdapter.buildPayload(reading);
}

export function buildShipPrompt(reading: ShipReading) {
  return shipAdapter.buildPrompt(reading);
}
